[package]
name = "all_to_all"
version = "0.1.0"
authors = ["charan n.a <charan1994@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.mpi]
git = "https://github.com/rsmpi/rsmpi.git"
default-features = false
